In [19]:
import pandas as pd
import numpy as np 

df = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding = "Latin-1")
#df_e = df.groupby("Element")['Stock Variation'].max()
df_e = df.groupby("Element")
for group_name, group_data in df_e:
    print(f'Group name: {group_name}')
    print(group_data)
df_e.max()

Group name: Domestic supply quantity
       Area Code      Area  Item Code                      Item  Element Code  \
1              4   Algeria       2501                Population          5301
15             4   Algeria       2905  Cereals - Excluding Beer          5301
31             4   Algeria       2511        Wheat and products          5301
47             4   Algeria       2805         Rice and products          5301
62             4   Algeria       2513       Barley and products          5301
...          ...       ...        ...                       ...           ...
60898        181  Zimbabwe       2769   Aquatic Animals, Others          5301
60906        181  Zimbabwe       2775            Aquatic Plants          5301
60916        181  Zimbabwe       2928             Miscellaneous          5301
60926        181  Zimbabwe       2680               Infant food          5301
60936        181  Zimbabwe       2899             Miscellaneous          5301

                        Element         Unit     Y2014    Y2015    Y2016  \
1      Domestic supply quantity  1000 tonnes      0.00      0.0      0.0
15     Domestic supply quantity  1000 tonnes  15353.00  16075.0  16056.0
31     Domestic supply quantity  1000 tonnes   9407.00   9780.0   9958.0
47     Domestic supply quantity  1000 tonnes    163.00    166.0    167.0
62     Domestic supply quantity  1000 tonnes   1702.00   1746.0   1781.0
...                         ...          ...       ...      ...      ...
60898  Domestic supply quantity  1000 tonnes      0.01      0.0      0.0
60906  Domestic supply quantity  1000 tonnes      0.00      0.0      0.0
60916  Domestic supply quantity  1000 tonnes     41.00     46.0     33.0
60926  Domestic supply quantity  1000 tonnes      0.00      0.0      0.0
60936  Domestic supply quantity  1000 tonnes     42.00     46.0     33.0

         Y2017    Y2018
1          0.0      0.0
15     15803.0  17004.0
31      9987.0  10472.0
47       173.0    170.0
62      1521.0   2225.0
...        ...      ...
60898      0.0      0.0
60906      0.0      0.0
60916     19.0     16.0
60926      0.0      0.0
60936     19.0     16.0

[5295 rows x 12 columns]
Group name: Export Quantity
       Area Code      Area  Item Code                      Item  Element Code  \
14             4   Algeria       2905  Cereals - Excluding Beer          5911
30             4   Algeria       2511        Wheat and products          5911
46             4   Algeria       2805         Rice and products          5911
61             4   Algeria       2513       Barley and products          5911
76             4   Algeria       2514        Maize and products          5911
...          ...       ...        ...                       ...           ...
60864        181  Zimbabwe       2765               Crustaceans          5911
60881        181  Zimbabwe       2767           Molluscs, Other          5911
60915        181  Zimbabwe       2928             Miscellaneous          5911
60925        181  Zimbabwe       2680               Infant food          5911
60935        181  Zimbabwe       2899             Miscellaneous          5911

               Element         Unit  Y2014  Y2015  Y2016  Y2017  Y2018
14     Export Quantity  1000 tonnes    3.0    7.0   7.00   10.0   17.0
30     Export Quantity  1000 tonnes    3.0    7.0   6.00   10.0   17.0
46     Export Quantity  1000 tonnes    NaN    0.0   0.00    0.0    0.0
61     Export Quantity  1000 tonnes    NaN    0.0   0.00    NaN    0.0
76     Export Quantity  1000 tonnes    0.0    0.0   0.00    0.0    0.0
...                ...          ...    ...    ...    ...    ...    ...
60864  Export Quantity  1000 tonnes    0.0    0.0   0.02    0.0    0.0
60881  Export Quantity  1000 tonnes    0.0    0.0   0.01    0.0    0.0
60915  Export Quantity  1000 tonnes    1.0    1.0   1.00    1.0    1.0
60925  Export Quantity  1000 tonnes    0.0    0.0   0.00    0.0    0.0
60935  Export Quantity  1000 tonnes    1.0    1.0   0.00    0.0    1.0

[4403 rows x 12 columns]
Group name: Fat supply quantity (g/capita/day)
       Area Code      Area  Item Code                      Item  Element Code  \
4              4   Algeria       2901               Grand Total           684
7              4   Algeria       2903          Vegetal Products           684
10             4   Algeria       2941           Animal Products           684
26             4   Algeria       2905  Cereals - Excluding Beer           684
42             4   Algeria       2511        Wheat and products           684
...          ...       ...        ...                       ...           ...
60904        181  Zimbabwe       2769   Aquatic Animals, Others           684
60912        181  Zimbabwe       2775            Aquatic Plants           684
60922        181  Zimbabwe       2928             Miscellaneous           684
60932        181  Zimbabwe       2680               Infant food           684
60942        181  Zimbabwe       2899             Miscellaneous           684

                                  Element          Unit  Y2014  Y2015  Y2016  \
4      Fat supply quantity (g/capita/day)  g/capita/day  80.06  79.36  77.40
7      Fat supply quantity (g/capita/day)  g/capita/day  53.84  54.72  52.04
10     Fat supply quantity (g/capita/day)  g/capita/day  26.22  24.64  25.37
26     Fat supply quantity (g/capita/day)  g/capita/day   6.84   6.78   6.83
42     Fat supply quantity (g/capita/day)  g/capita/day   5.39   5.31   5.37
...                                   ...           ...    ...    ...    ...
60904  Fat supply quantity (g/capita/day)  g/capita/day   0.00   0.00   0.00
60912  Fat supply quantity (g/capita/day)  g/capita/day   0.00   0.00   0.00
60922  Fat supply quantity (g/capita/day)  g/capita/day   0.04   0.05   0.03
60932  Fat supply quantity (g/capita/day)  g/capita/day   0.00   0.00   0.00
60942  Fat supply quantity (g/capita/day)  g/capita/day   0.04   0.05   0.03

       Y2017  Y2018
4      80.19  77.28
7      55.59  54.57
10     24.60  22.71
26      6.63   6.58
42      5.25   5.12
...      ...    ...
60904   0.00   0.00
60912   0.00   0.00
60922   0.02   0.02
60932   0.00   0.00
60942   0.02   0.01

[5023 rows x 12 columns]
Group name: Feed
       Area Code      Area  Item Code                      Item  Element Code  \
16             4   Algeria       2905  Cereals - Excluding Beer          5521
32             4   Algeria       2511        Wheat and products          5521
48             4   Algeria       2805         Rice and products          5521
63             4   Algeria       2513       Barley and products          5521
78             4   Algeria       2514        Maize and products          5521
...          ...       ...        ...                       ...           ...
60706        181  Zimbabwe       2740              Butter, Ghee          5521
60787        181  Zimbabwe       2948   Milk - Excluding Butter          5521
60801        181  Zimbabwe       2848   Milk - Excluding Butter          5521
60815        181  Zimbabwe       2960             Fish, Seafood          5521
60845        181  Zimbabwe       2763              Pelagic Fish          5521

      Element         Unit    Y2014    Y2015    Y2016    Y2017    Y2018
16       Feed  1000 tonnes  4725.00  5070.00  4838.00  4667.00  5266.00
32       Feed  1000 tonnes   550.00   592.00   584.00   587.00   665.00
48       Feed  1000 tonnes     5.00     1.00     1.00     2.00     0.00
63       Feed  1000 tonnes  1028.00  1075.00  1082.00   909.00  1400.00
78       Feed  1000 tonnes  3077.00  3309.00  3084.00  3102.00  3090.00
...       ...          ...      ...      ...      ...      ...      ...
60706    Feed  1000 tonnes     0.00     0.00     0.00     0.00     0.00
60787    Feed  1000 tonnes     7.00     8.00     7.00     6.00     6.00
60801    Feed  1000 tonnes     7.00     8.00     7.00     6.00     6.00
60815    Feed  1000 tonnes     7.25     7.04     4.37     0.66     0.66
60845    Feed  1000 tonnes     7.25     7.04     4.37     0.66     0.66

[1319 rows x 12 columns]
Group name: Food
       Area Code      Area  Item Code                      Item  Element Code  \
22             4   Algeria       2905  Cereals - Excluding Beer          5142
38             4   Algeria       2511        Wheat and products          5142
53             4   Algeria       2805         Rice and products          5142
68             4   Algeria       2513       Barley and products          5142
83             4   Algeria       2514        Maize and products          5142
...          ...       ...        ...                       ...           ...
60900        181  Zimbabwe       2769   Aquatic Animals, Others          5142
60908        181  Zimbabwe       2775            Aquatic Plants          5142
60918        181  Zimbabwe       2928             Miscellaneous          5142
60928        181  Zimbabwe       2680               Infant food          5142
60938        181  Zimbabwe       2899             Miscellaneous          5142

      Element         Unit    Y2014   Y2015   Y2016   Y2017   Y2018
22       Food  1000 tonnes  8546.00  8729.0  9001.0  8941.0  9219.0
38       Food  1000 tonnes  7258.00  7425.0  7670.0  7701.0  7795.0
53       Food  1000 tonnes   158.00   164.0   166.0   171.0   170.0
68       Food  1000 tonnes   488.00   478.0   486.0   416.0   621.0
83       Food  1000 tonnes   640.00   657.0   669.0   644.0   628.0
...       ...          ...      ...     ...     ...     ...     ...
60900    Food  1000 tonnes     0.01     0.0     0.0     0.0     0.0
60908    Food  1000 tonnes     0.00     0.0     0.0     0.0     0.0
60918    Food  1000 tonnes    42.00    46.0    33.0    19.0    16.0
60928    Food  1000 tonnes     0.00     0.0     0.0     0.0     0.0
60938    Food  1000 tonnes    42.00    46.0    33.0    19.0    16.0

[4941 rows x 12 columns]
Group name: Food supply (kcal/capita/day)
       Area Code      Area  Item Code                      Item  Element Code  \
2              4   Algeria       2901               Grand Total           664
5              4   Algeria       2903          Vegetal Products           664
8              4   Algeria       2941           Animal Products           664
24             4   Algeria       2905  Cereals - Excluding Beer           664
40             4   Algeria       2511        Wheat and products           664
...          ...       ...        ...                       ...           ...
60902        181  Zimbabwe       2769   Aquatic Animals, Others           664
60910        181  Zimbabwe       2775            Aquatic Plants           664
60920        181  Zimbabwe       2928             Miscellaneous           664
60930        181  Zimbabwe       2680               Infant food           664
60940        181  Zimbabwe       2899             Miscellaneous           664

                             Element             Unit   Y2014   Y2015   Y2016  \
2      Food supply (kcal/capita/day)  kcal/capita/day  3377.0  3379.0  3372.0
5      Food supply (kcal/capita/day)  kcal/capita/day  2932.0  2958.0  2941.0
8      Food supply (kcal/capita/day)  kcal/capita/day   444.0   421.0   431.0
24     Food supply (kcal/capita/day)  kcal/capita/day  1680.0  1682.0  1699.0
40     Food supply (kcal/capita/day)  kcal/capita/day  1432.0  1435.0  1453.0
...                              ...              ...     ...     ...     ...
60902  Food supply (kcal/capita/day)  kcal/capita/day     0.0     0.0     0.0
60910  Food supply (kcal/capita/day)  kcal/capita/day     0.0     0.0     0.0
60920  Food supply (kcal/capita/day)  kcal/capita/day     3.0     4.0     3.0
60930  Food supply (kcal/capita/day)  kcal/capita/day     0.0     0.0     0.0
60940  Food supply (kcal/capita/day)  kcal/capita/day     3.0     4.0     3.0

        Y2017   Y2018
2      3341.0  3322.0
5      2921.0  2932.0
8       421.0   390.0
24     1656.0  1672.0
40     1430.0  1419.0
...       ...     ...
60902     0.0     0.0
60910     0.0     0.0
60920     2.0     1.0
60930     0.0     0.0
60940     1.0     1.0

[5014 rows x 12 columns]
Group name: Food supply quantity (kg/capita/yr)
       Area Code      Area  Item Code                      Item  Element Code  \
23             4   Algeria       2905  Cereals - Excluding Beer           645
39             4   Algeria       2511        Wheat and products           645
54             4   Algeria       2805         Rice and products           645
69             4   Algeria       2513       Barley and products           645
84             4   Algeria       2514        Maize and products           645
...          ...       ...        ...                       ...           ...
60901        181  Zimbabwe       2769   Aquatic Animals, Others           645
60909        181  Zimbabwe       2775            Aquatic Plants           645
60919        181  Zimbabwe       2928             Miscellaneous           645
60929        181  Zimbabwe       2680               Infant food           645
60939        181  Zimbabwe       2899             Miscellaneous           645

                                   Element Unit   Y2014   Y2015   Y2016  \
23     Food supply quantity (kg/capita/yr)   kg  219.56  219.72  221.98
39     Food supply quantity (kg/capita/yr)   kg  186.46  186.90  189.14
54     Food supply quantity (kg/capita/yr)   kg    4.07    4.14    4.09
69     Food supply quantity (kg/capita/yr)   kg   12.54   12.03   11.98
84     Food supply quantity (kg/capita/yr)   kg   16.44   16.55   16.49
...                                    ...  ...     ...     ...     ...
60901  Food supply quantity (kg/capita/yr)   kg    0.00    0.00    0.00
60909  Food supply quantity (kg/capita/yr)   kg    0.00    0.00    0.00
60919  Food supply quantity (kg/capita/yr)   kg    3.06    3.33    2.35
60929  Food supply quantity (kg/capita/yr)   kg    0.00    0.00    0.00
60939  Food supply quantity (kg/capita/yr)   kg    3.06    3.33    2.35

        Y2017   Y2018
23     216.02  218.31
39     186.07  184.58
54       4.14    4.03
69      10.05   14.70
84      15.57   14.86
...       ...     ...
60901    0.00    0.00
60909    0.00    0.00
60919    1.34    1.09
60929    0.00    0.01
60939    1.33    1.08

[4905 rows x 12 columns]
Group name: Import Quantity
       Area Code      Area  Item Code                      Item  Element Code  \
12             4   Algeria       2905  Cereals - Excluding Beer          5611
28             4   Algeria       2511        Wheat and products          5611
44             4   Algeria       2805         Rice and products          5611
59             4   Algeria       2513       Barley and products          5611
74             4   Algeria       2514        Maize and products          5611
...          ...       ...        ...                       ...           ...
60897        181  Zimbabwe       2769   Aquatic Animals, Others          5611
60905        181  Zimbabwe       2775            Aquatic Plants          5611
60913        181  Zimbabwe       2928             Miscellaneous          5611
60923        181  Zimbabwe       2680               Infant food          5611
60933        181  Zimbabwe       2899             Miscellaneous          5611

               Element         Unit     Y2014    Y2015    Y2016    Y2017  \
12     Import Quantity  1000 tonnes  12604.00  13983.0  13523.0  13039.0
28     Import Quantity  1000 tonnes   7461.00   8531.0   8255.0   8105.0
44     Import Quantity  1000 tonnes    171.00    164.0    162.0    190.0
59     Import Quantity  1000 tonnes    805.00    797.0    916.0    567.0
74     Import Quantity  1000 tonnes   4148.00   4450.0   4159.0   4161.0
...                ...          ...       ...      ...      ...      ...
60897  Import Quantity  1000 tonnes      0.01      0.0      0.0      0.0
60905  Import Quantity  1000 tonnes      0.00      0.0      0.0      0.0
60913  Import Quantity  1000 tonnes     42.00     47.0     34.0     15.0
60923  Import Quantity  1000 tonnes      0.00      0.0      0.0      0.0
60933  Import Quantity  1000 tonnes     42.00     47.0     33.0     15.0

         Y2018
12     13182.0
28      8434.0
44       207.0
59       402.0
74      4126.0
...        ...
60897      0.0
60905      0.0
60913     16.0
60923      0.0
60933     16.0

[5139 rows x 12 columns]
Group name: Losses
       Area Code      Area  Item Code                      Item  Element Code  \
18             4   Algeria       2905  Cereals - Excluding Beer          5123
34             4   Algeria       2511        Wheat and products          5123
50             4   Algeria       2805         Rice and products          5123
65             4   Algeria       2513       Barley and products          5123
80             4   Algeria       2514        Maize and products          5123
...          ...       ...        ...                       ...           ...
60729        181  Zimbabwe       2737        Fats, Animals, Raw          5123
60760        181  Zimbabwe       2949                      Eggs          5123
60774        181  Zimbabwe       2744                      Eggs          5123
60788        181  Zimbabwe       2948   Milk - Excluding Butter          5123
60802        181  Zimbabwe       2848   Milk - Excluding Butter          5123

      Element         Unit   Y2014   Y2015   Y2016   Y2017   Y2018
18     Losses  1000 tonnes  1084.0  1203.0  1148.0  1121.0  1253.0
34     Losses  1000 tonnes   690.0   781.0   747.0   736.0   868.0
50     Losses  1000 tonnes     0.0     0.0     0.0     0.0     0.0
65     Losses  1000 tonnes   103.0   107.0   108.0    91.0    89.0
80     Losses  1000 tonnes   288.0   309.0   288.0   290.0   289.0
...       ...          ...     ...     ...     ...     ...     ...
60729  Losses  1000 tonnes     0.0     0.0     0.0     0.0     0.0
60760  Losses  1000 tonnes     3.0     2.0     2.0     2.0     2.0
60774  Losses  1000 tonnes     3.0     2.0     2.0     2.0     2.0
60788  Losses  1000 tonnes    39.0    39.0    39.0    38.0    39.0
60802  Losses  1000 tonnes    39.0    39.0    39.0    38.0    39.0

[2009 rows x 12 columns]
Group name: Other uses (non-food)
       Area Code      Area  Item Code                      Item  Element Code  \
20             4   Algeria       2905  Cereals - Excluding Beer          5154
36             4   Algeria       2511        Wheat and products          5154
150            4   Algeria       2907             Starchy Roots          5154
174            4   Algeria       2531     Potatoes and products          5154
228            4   Algeria       2909        Sugar & Sweeteners          5154
...          ...       ...        ...                       ...           ...
60874        181  Zimbabwe       2766               Cephalopods          5154
60883        181  Zimbabwe       2767           Molluscs, Other          5154
60891        181  Zimbabwe       2961   Aquatic Products, Other          5154
60899        181  Zimbabwe       2769   Aquatic Animals, Others          5154
60907        181  Zimbabwe       2775            Aquatic Plants          5154

                     Element         Unit  Y2014  Y2015  Y2016  Y2017  Y2018
20     Other uses (non-food)  1000 tonnes  787.0  847.0  835.0  840.0  951.0
36     Other uses (non-food)  1000 tonnes  787.0  847.0  835.0  840.0  951.0
150    Other uses (non-food)  1000 tonnes  572.0  559.0  577.0  566.0  570.0
174    Other uses (non-food)  1000 tonnes  572.0  559.0  577.0  566.0  570.0
228    Other uses (non-food)  1000 tonnes  209.0  227.0  221.0  252.0  307.0
...                      ...          ...    ...    ...    ...    ...    ...
60874  Other uses (non-food)  1000 tonnes    0.0    0.0    0.0    0.0    0.0
60883  Other uses (non-food)  1000 tonnes    0.0    0.0    0.0    0.0    0.0
60891  Other uses (non-food)  1000 tonnes    0.0    0.0    0.0    0.0    0.0
60899  Other uses (non-food)  1000 tonnes    0.0    0.0    0.0    0.0    0.0
60907  Other uses (non-food)  1000 tonnes    0.0    0.0    0.0    0.0    0.0

[1732 rows x 12 columns]
Group name: Processing

,Area Code,Area,Item Code,Item,Element Code,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,,,,
Domestic supply quantity,276,Zimbabwe,2961,Yams,5301,1000 tonnes,108756.00,110798.00,116483.00,112625.00,117038.00
Export Quantity,276,Zimbabwe,2961,Yams,5911,1000 tonnes,39686.00,52578.00,35420.00,34641.00,34641.00
Fat supply quantity (g/capita/day),276,Zimbabwe,2961,Yams,684,g/capita/day,93.73,96.79,94.33,97.13,94.94
Feed,276,Zimbabwe,2960,Yams,5521,1000 tonnes,29797.00,30472.00,31607.00,29580.00,31567.00
Food,276,Zimbabwe,2961,Yams,5142,1000 tonnes,49014.00,50705.00,52612.00,51220.00,54077.00
Food supply (kcal/capita/day),276,Zimbabwe,2961,Yams,664,kcal/capita/day,3435.00,3454.00,3451.00,3457.00,3450.00
Food supply quantity (kg/capita/yr),276,Zimbabwe,2961,Yams,645,kg,428.27,418.21,419.48,433.38,443.56
Import Quantity,276,Zimbabwe,2961,Yams,5611,1000 tonnes,19582.00,18824.00,19858.00,18627.00,18036.00
Losses,276,Zimbabwe,2949,Yams,5123,1000 tonnes,9807.00,9999.00,10432.00,10342.00,10355.00
Other uses (non-food),276,Zimbabwe,2961,Yams,5154,1000 tonnes,12552.00,6001.00,6099.00,17219.00,17221.00
Processing,276,Zimbabwe,2948,Wine,5131,1000 tonnes,18383.00,21609.00,21739.00,22174.00,22609.00
Production,276,Zimbabwe,2961,Yams,5511,1000 tonnes,109593.00,111663.00,119330.00,117702.00,118172.00
Protein supply quantity (g/capita/day),276,Zimbabwe,2961,Yams,674,g/capita/day,100.34,100.33,100.94,100.10,101.08
Residuals,276,Zimbabwe,2949,Yams,5170,1000 tonnes,16697.00,16136.00,18077.00,17476.00,17323.00
Seed,276,Zimbabwe,2960,Yams,5527,1000 tonnes,1258.00,1352.00,1402.00,1453.00,1474.00
Stock Variation,276,Zimbabwe,2961,Yams,5072,1000 tonnes,4569.00,3418.00,3266.00,5089.00,2226.00
Total Population - Both sexes,276,Zimbabwe,2501,Population,511,1000 persons,176405.00,181137.00,185960.00,190873.00,195875.00
Tourist consumption,193,Sao Tome and Principe,2949,Yams,5171,1000 tonnes,62.00,48.00,6.00,6.00,6.00

In [49]:
#finding the country with the highest sum in 2017
df_y = df[['Y2017','Area']].groupby('Area')
for x,y in df_y:
    print(f'Group_name: {x}')
    print(y['Y2017'].sum())

Group_name: Algeria
325644.27
Group_name: Angola
229159.57
Group_name: Benin
124771.22
Group_name: Botswana
22101.3
Group_name: Burkina Faso
101855.07
Group_name: Cabo Verde
14650.740000000002
Group_name: Cameroon
232030.43
Group_name: Central African Republic
29937.000000000004
Group_name: Chad
71594.68
Group_name: Comoros
59.84
Group_name: Congo
41181.67999999999
Group_name: Côte d'Ivoire
224599.01
Group_name: Djibouti
22729.91
Group_name: Egypt
866379.92
Group_name: Eswatini
54343.33000000001
Group_name: Ethiopia
448683.75999999995
Group_name: Ethiopia PDR
0.0
Group_name: Gabon
27979.64
Group_name: Gambia
23154.179999999997
Group_name: Ghana
337599.06
Group_name: Guinea
98138.87
Group_name: Guinea-Bissau
19102.769999999997
Group_name: Kenya
264660.66
Group_name: Lesotho
21267.960000000003
Group_name: Liberia
29342.200000000004
Group_name: Madagascar
131197.73
Group_name: Malawi
181098.71
Group_name: Mali
149928.33
Group_name: Mauritania
156665.46
Group_name: Mauritius
51114.829999999994
Group_name: Morocco
388495.36
Group_name: Mozambique
161407.97999999998
Group_name: Namibia
29874.89
Group_name: Niger
126707.58000000002
Group_name: Nigeria
1483268.23
Group_name: Rwanda
73663.69
Group_name: Sao Tome and Principe
12662.630000000001
Group_name: Senegal
95681.15
Group_name: Seychelles
442.34
Group_name: Sierra Leone
55311.33
Group_name: South Africa
517590.54
Group_name: Sudan
239931.91999999998
Group_name: Sudan (former)
0.0
Group_name: Togo
49841.880000000005
Group_name: Tunisia
124167.20000000001
Group_name: Uganda
213950.38
Group_name: United Republic of Tanzania
322616.85
Group_name: Zambia
103223.77
Group_name: Zimbabwe
75919.34

In [52]:
#year with the highest sum of stock variation
df_y = df.groupby('Element')
for x,y in df_y:
    if x == 'Stock Variation':
           print(y[['Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018']].sum())

Y2014    58749.83
Y2015    34910.99
Y2016    33140.12
Y2017    54316.91
Y2018    20577.91
dtype: float64

In [40]:
#Total number and percentage of missing data in 2014
n_sum = df['Y2014'].isnull().sum()
per = (int(n_sum)/len(df['Y2014']))* 100
print(f'Sum = {n_sum}\nPercentage = {round(per, 3)}')

Sum = 1589
Percentage = 2.607

In [44]:
#The sum of wine produced in 2015 and 2018
df_i = df.groupby("Item")
for x,y in df_i:
    if x == 'Wine':
        print(y[['Y2015','Y2018']].sum())

Y2015    4251.81
Y2018    4039.32
dtype: float64

In [27]:
#printing the total number of unique countries 
df_u = df['Area'].unique()
print(len(df_u))

49

In [33]:
#sum of processing in Y2017
df_y = df.groupby('Element')
for x,y in df_y:
    if x == 'Processing':
        print(y['Y2017'].sum())

292836.0

In [ ]:
#finding the country with the 7th lowest  sum in 2017
df_y = df[['Y2017','Area']].groupby('Area')
for x,y in df_y:
    print(f'Group_name: {x}')
    print(y['Y2017'].sum())